[server]
runOnSave = false
port = 8501
headless = true

[theme]
base = "light"
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f6fa"
textColor = "#222222"
font = "sans serif"
